title: Laurel's Home
views:
  - title: welcome
    id: welcome
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
    # weather card
      - type: custom:weather-card
        entity: weather.dark_sky
        name: Weather2
    # swipe card
      - type: custom:swipe-card
        card_width: '300px'
        start_card: 2
        parameters:
          effect: 'coverflow'
          grabCursor: true
          centeredSlides: true
          slidesPerView: 'auto'
          coverflowEffect:
            rotate: 50
            stretch: 0
            depth: 100
            modifier: 1
            slideShadows : true
          pagination:
            type: 'bullets'
        cards:
          - type: sensor
            entity: sensor.current_version
            name: Current Version
            line_color: '#36A2EB'
            line_width: 8
          - type: sensor
            entity: sensor.date_time
            name: Date & Time
            line_color: '#ffce57'
            line_width: 8

###################
#   Cameras Tab   #
###################
        
  - title: Cameras
    id: cameras
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
    # camera feed
      - type: picture-glance        
        entities:
          - camera.living_room_camera
        camera_image: camera.living_room_camera
      - type: picture-glance        
        entities:
          - camera.outside_camera
        camera_image: camera.outside_camera
    # camera battery level
      - type: custom:bignumber-card
        title: Living Room Camera Battery Level
        entity: sensor.battery_level_living_room_camera
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 100
            style: 'var(--label-badge-green)'
          - value: 70
            style: 'var(--label-badge-yellow)'
          - value: 25
            style: 'var(--label-badge-red)'
      - type: custom:bignumber-card
        title: Outside Camera Battery Level
        entity: sensor.battery_level_outside_camera
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 100
            style: 'var(--label-badge-green)'
          - value: 70
            style: 'var(--label-badge-yellow)'
          - value: 25
            style: 'var(--label-badge-red)'
      - type: custom:bignumber-card
        title: Living Room Camera Signal Strength
        entity: sensor.signal_strength_living_room_camera
        scale: 30px
        from: bottom
        min: 0
        max: 5
        severity:
          - value: 4
            style: 'var(--label-badge-green)'
          - value: 3
            style: 'var(--label-badge-yellow)'
          - value: 2
            style: 'var(--label-badge-red)'
      - type: custom:bignumber-card
        title: Outside Camera Signal Strength
        entity: sensor.signal_strength_outside_camera
        scale: 30px
        from: bottom
        min: 0
        max: 5
        severity:
          - value: 4
            style: 'var(--label-badge-green)'
          - value: 3
            style: 'var(--label-badge-yellow)'
          - value: 2
            style: 'var(--label-badge-red)'
            
####################
#  Thermostat Tab  #
####################          
  - title: Thermostat
    id: thermostat
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: custom:simple-thermostat
        entity: climate.hallway
        name: Thermostat
        decimals: 1
        step_size: 1
        sensors:
          - entity: sensor.hallway_thermostat_humidity
            name: Humidity
          - attribute: min_temp
            name: Min Temp
          - attribute: max_temp
            name: Max Temp
            
#####################
#  Automations Tab  #
#####################
         
  - title: Automations
    id: automations
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - id: automations 
        type: entity-filter
        entities:
        - automation.check_sensor_value_and_show_notification        
        - automation.reload_groups
        - automation.restart_hass
        - automation.send_text_msg
        - automation.startup_notification
        - automation.ios_notification          
        state_filter:
          - 'off'
          - 'on'          
        card:
          title: Automations
      - id: light_automations 
        type: entity-filter
        entities:
        - automation.turn_laurels_lights_on        
        - automation.turn_laurels_lights_off       
        state_filter:
          - 'off'
          - 'on'          
        card:
          title: Light Automations        

##################
#   Lights Tab   #
##################

    # View tab title.         
  - title: Lights
    # Unique id for direct access /lovelace/${id} and editing it from the UI.  
    id: outside_lights
    # Optional background (overwrites the global background).    
    background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.    
    theme: dark-mode
    cards:
        # The filter card will filter entities for their state
        # Every card needs an ID, for it to be edited from the UI.    
      - id: outsideLights 
        type: entity-filter
        entities:
          - light.lamp_post_light
          - light.front_door_light
          - light.garage_light          
        state_filter:
          - 'off'
          - 'on'
        card:
          type: glance
          title: Outside Lights       
      - id: insideLights 
        type: entity-filter
        entities:
          - light.spare_bedroom_light
          - light.living_room_lamp  
        state_filter:
          - 'off'
          - 'on'          
        card:
          type: glance
          title: Inside Lights
          
      - type: light
        entity: light.front_door_light
      - type: light
        entity: light.garage_light
      - type: light
        entity: light.lamp_post_light
      - type: light
        entity: light.spare_bedroom_light
      - type: light
        entity: light.living_room_lamp

####################
#   Switches Tab   #
####################
         
  - title: Switches
    id: switches
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: entity-button
        entity: switch.outlet      
          
####################
#  Monitoring Tab  #
####################
         
  - title: Monitoring
    id: monitoring
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:        
      - type: custom:swipe-card
        card_width: '400px'
        start_card: 2
        parameters:
          effect: 'coverflow'
          grabCursor: true
          centeredSlides: true
          slidesPerView: 'auto'
          coverflowEffect:
            rotate: 50
            stretch: 0
            depth: 100
            modifier: 1
            slideShadows : true
          pagination:
            type: 'bullets'
        cards:
          - type: sensor
            entity: sensor.time_online
            name: Online Time
            line_color: '#ffce57'
            line_width: 8        
        
################
#    Map Tab   #
################
         
  - title: Map
    id: map
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: map
        default_zoom: 15      
        name: Map
        entities:
          - zone.home

#################
#  History Tab  #
#################
         
  - title: History
    id: history
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: history-graph
        name: History
        entities:
          - light.lamp_post_light
          - light.front_door_light
          - light.garage_light
          - light.laurels_room
          - light.spare_bedroom_light          

resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.min.js
    type: module
  - url: /local/bignumber-card.js?v=1
    type: js
  - url: /local/weather-card.js
    type: module
  - url: /local/simple-thermostat.js?v=1
    type: module    

# Documentation Links
# 1. https://www.awesome-ha.com/#lovelace-ui
# 2. https://github.com/ciotlosm/custom-lovelace
# 3. https://community.home-assistant.io/t/lovelace-swiper-card/72447?u=frenck
# 4. https://github.com/nervetattoo/simple-thermostat

       